# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: 'edcbdfac3319b87104e720c4b48f4556'
    apiKey: '7dba8f47cec959a969b1b721aec8cc5e59fc3aa48cf54f0c4b72444fd06830139e0280dc81373e2e27b7378251fc683d055d781619f5e01b0b90c0669f3beeb0'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    importResults: true
    maximumWaitTime: '360'
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
